# render.yaml
services:
  - type: web
    name: reader
    env: java
    plan: starter
    buildCommand: mvn package
    startCommand: java -jar target/reader-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
